name: Deployment

on:
  push:
    branches:
      - feature/**
      - fix/**
      - develop
      - master

  workflow_dispatch:

jobs:
  build-and-validate:
    uses: ./.github/workflows/build-and-validate.yml

  deployment:
    runs-on: ubuntu-latest
    needs: build-and-validate
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: Restore Build
        uses: actions/cache/restore@v6
        with:
          path: dist
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Deployment
        run: echo "Deployment Successful!"
