name: Deployment

on:
  push:
    branches:
      - feature/**
      - fix/**
      - develop
      - master

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/validate.yml
      - name: Restore Build
        uses: actions/cache/restore@v6
        with:
          path: /dist
          key: ${{ runner.os }} ${{ hashFiles('**/yarn.lock') }}
      - name: Deployment
        run: echo "Deployment Successful!"
