name: Validate

on:
  workflow_call:
    outputs:
      build-cache-key:
        description: 'Cache key, used to restore build cache'
        value: ${{ jobs.validate.outputs.build-cache-key }}
      build-cache-hit:
        description: 'Build cache was hit'
        value: ${{ jobs.validate.outputs.build-cache-hit }}
      modules-cache-key:
        description: 'Cache key, used to restore modules cache'
        value: ${{ jobs.validate.outputs.modules-cache-key }}
      modules-cache-hit:
        description: 'Modules cache was hit'
        value: ${{ jobs.validate.outputs.modules-cache-hit }}

jobs:
  validate:
    name: Validate App
    runs-on: ubuntu-latest
    outputs:
      build-cache-key: ${{ steps.key-gen.outputs.build }}
      build-cache-hit: ${{ steps.build-cache.outputs.cache-hit }}
      modules-cache-key: ${{ steps.key-gen.outputs.modules }}
      modules-cache-hit: ${{ steps.modules-cache.outputs.cache-hit }}
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: Setup Modules
        run: npm ci
      - name: Test Lint
        run: npm run lint
      - name: Unit Test
        run: npm run test:unit
      - name: Build
        run: npm run build
      - name: Setup Playwright
        run: npx playwright install chromium --with-deps
      - name: E2E Test
        run: npm run test:e2e
        env:
          CI: true
      - name: Upload E2E Trace
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 1
      - name: Generate Build Cache Key
        id: key-gen
        run: |
          build_cache_key="build=build-${{ github.sha }}-$(/bin/date -u "+%Y%m%d-%H%M%S")"
          modules_cache_key="modules=modules-${{ hashFiles('**/package-lock.json') }}"

          echo $build_cache_key >> $GITHUB_OUTPUT
          echo $modules_cache_key >> $GITHUB_OUTPUT

          echo "Build cache key: $build_cache_key"
          echo "Modules cache key: $build_cache_key"
      - name: Cache Build
        id: build-cache
        uses: actions/cache/save@v6
        with:
          key: ${{ steps.key-gen.outputs.build }}
          path: dist
      - name: Cache Modules
        id: modules-cache
        uses: actions/cache/save@v6
        with:
          key: ${{ steps.key-gen.outputs.modules }}
          path: node_modules
