name: Validate

on:
  workflow_call:

jobs:
  validate:
    name: Validate App
    runs-on: ubuntu-latest
    outputs:
      build-cache-key: ${{ steps.key-gen.outputs.build }}
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: yarn
      - name: Setup Yarn
        run: corepack enable
      - name: Setup Modules
        run: yarn install --immutable
      - name: Test Lint
        run: yarn lint
      - name: Unit Test
        run: yarn test:unit
      - name: Build
        run: yarn build
      # - name: Upload Build
      #   uses: actions/upload-artifact@v7
      #   with:
      #     path: dist
      #     name: app-build
      #     retention-days: 1
      - name: Setup Playwright
        run: npx playwright install --with-deps
      - name: E2E Test
        run: yarn test:e2e
        env:
          CI: true
      - name: Upload E2E Trace
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 1
      - name: Generate Build Cache Key
        id: key-gen
        run: |
          echo "build=${{ github.sha }}-$(/bin/date -u "+%Y%m%d-%H%M%S") >> $GITHUB_OUTPUT"
          echo "Cache key: ${{ steps.key-gen.outputs.build }}"
      - name: Cache Build
        uses: actions/cache/save@v5
        with:
          key: ${{ steps.key-gen.outputs.build }}
          path: |
            dist
            node_modules
