name: Validate PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      - develop
      - fix/**
      - feature/**

jobs:
  validate:
    name: Validate PR
    uses: ./.github/workflows/validate.yml
